/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.pessoas_control;
import Model.pessoas_model;
import Model.tipo_pessoas;
import javax.swing.JOptionPane;

/**
 *
 * @author Andre
 */
public class form_alterar_pessoa extends javax.swing.JDialog {

    private int tipoPessoa;
    private int idPessoa;

    /**
     * Creates new form form_alterar_pessoa
     */
    public form_alterar_pessoa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        group_radio.add(radio_cpf);
        group_radio.add(radio_cnpj);
    }

    /**
     * preenche os campos de acordo com o id selecionado na tela de localização
     *
     * @param id_pessoa
     * @param tipo
     */
    private void preencherCampos(int id_pessoa, int tipo) {

        if (tipo == tipo_pessoas.CNPJ) {

            pessoas_model juridica;
            pessoas_control recuperar = new pessoas_control();
            juridica = recuperar.capturarInfoPessoasEmpresa(id_pessoa);

            radio_cnpj.setEnabled(true);
//            radio_cpf.setEnabled(true);
            radio_cnpj.setSelected(true);
            lbl_tipo_cnpj_cpf.setText("CNPJ:");
            campo_nome.setText(juridica.getNome());
            campo_cnpj_cpf.setText(juridica.getCnpj());

            btn_salvar_alteracao.setEnabled(true);
//            System.out.println("tipo pessoa: " + this.tipoPessoa);

        } else if (tipo == tipo_pessoas.CPF) {

            pessoas_model fisica;
            pessoas_control control = new pessoas_control();
            fisica = control.capturarInfoPessoasEmpresa(id_pessoa);

            radio_cpf.setEnabled(true);
//            radio_cnpj.setEnabled(true);
            radio_cpf.setSelected(true);
            lbl_tipo_cnpj_cpf.setText("CPF:");
            campo_nome.setText(fisica.getNome());
            campo_cnpj_cpf.setText(fisica.getCpf());

            btn_salvar_alteracao.setEnabled(true);
//            System.out.println("tipo pessoa: " + this.tipoPessoa);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_radio = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campo_nome = new javax.swing.JTextField();
        lbl_tipo_cnpj_cpf = new javax.swing.JLabel();
        campo_cnpj_cpf = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        radio_cpf = new javax.swing.JRadioButton();
        radio_cnpj = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        btn_salvar_alteracao = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar dados");

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/alter user.png"))); // NOI18N
        jLabel1.setText("Ateração de dados pessoa/empresa");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Alteração de dados"));

        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        campo_nome.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N

        lbl_tipo_cnpj_cpf.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbl_tipo_cnpj_cpf.setText("CPF/CNPJ:");

        campo_cnpj_cpf.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo pessoa"));

        radio_cpf.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        radio_cpf.setText("Pessoa Fisica(CPF)");
        radio_cpf.setEnabled(false);
        radio_cpf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_cpfItemStateChanged(evt);
            }
        });

        radio_cnpj.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        radio_cnpj.setText("Pessoa Juridica(CNPJ)");
        radio_cnpj.setEnabled(false);
        radio_cnpj.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_cnpjItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radio_cpf)
                    .addComponent(radio_cnpj))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radio_cpf)
                .addGap(18, 18, 18)
                .addComponent(radio_cnpj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tipo_cnpj_cpf)
                    .addComponent(jLabel2))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_cnpj_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(campo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tipo_cnpj_cpf)
                            .addComponent(campo_cnpj_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_salvar_alteracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/confirm_user.png"))); // NOI18N
        btn_salvar_alteracao.setToolTipText("Salvar alteração");
        btn_salvar_alteracao.setEnabled(false);
        btn_salvar_alteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_alteracaoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/localizar_pessoas.png"))); // NOI18N
        jButton1.setToolTipText("Localizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_salvar_alteracao)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_salvar_alteracao)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        form_localizar_pessoas localizar = new form_localizar_pessoas(null, true);
        localizar.setVisible(true);

        if (localizar.codigo_pessoa != 0) {

            preencherCampos(localizar.codigo_pessoa, localizar.tipo_cpf_cnpj);
            this.idPessoa = localizar.codigo_pessoa;

            // aqui indicamos qual metodo iremos utilizar na atualização
            // se será pessoa JURIDICA ou FISICA
            this.tipoPessoa = localizar.tipo_cpf_cnpj;

        } else {
            JOptionPane.showMessageDialog(this, "Ops... nenhuma pessoa foi selecinada", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void radio_cpfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_cpfItemStateChanged
        // definimos valor ao atributo tipoPessoa, assim se houver alteração no tipo de pessoa
        // iremos salvar as alterações corretamente

        this.tipoPessoa = tipo_pessoas.CPF;
    }//GEN-LAST:event_radio_cpfItemStateChanged

    private void radio_cnpjItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_cnpjItemStateChanged
        // definimos valor ao atributo tipoPessoa, assim se houver alteração no tipo de pessoa
        // iremos salvar as alterações corretamente

        this.tipoPessoa = tipo_pessoas.CNPJ;
    }//GEN-LAST:event_radio_cnpjItemStateChanged

    private void btn_salvar_alteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_alteracaoActionPerformed
        // atualiza as informações
        pessoas_model pessoaEmpresa = new pessoas_model();
        pessoas_control control = new pessoas_control();

        if (this.tipoPessoa == tipo_pessoas.CNPJ) {

            pessoaEmpresa.setNome(campo_nome.getText());
            pessoaEmpresa.setCnpj(campo_cnpj_cpf.getText());

            control.atualizarCadastrPessoa(pessoaEmpresa, tipoPessoa, idPessoa);

        } else if (this.tipoPessoa == tipo_pessoas.CPF) {

            pessoaEmpresa.setNome(campo_nome.getText());
            pessoaEmpresa.setCpf(campo_cnpj_cpf.getText());

            control.atualizarCadastrPessoa(pessoaEmpresa, tipoPessoa, idPessoa);
        }
    }//GEN-LAST:event_btn_salvar_alteracaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_alterar_pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_alterar_pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_alterar_pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_alterar_pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form_alterar_pessoa dialog = new form_alterar_pessoa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salvar_alteracao;
    private javax.swing.JTextField campo_cnpj_cpf;
    private javax.swing.JTextField campo_nome;
    private javax.swing.ButtonGroup group_radio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_tipo_cnpj_cpf;
    private javax.swing.JRadioButton radio_cnpj;
    private javax.swing.JRadioButton radio_cpf;
    // End of variables declaration//GEN-END:variables
}
