/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.pessoas_control;
import Model.pessoas_model;
import Model.tipo_pessoas;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andre
 */
public class form_localizar_pessoas extends javax.swing.JDialog {

    int codigo_pessoa = 0;
    int tipo_cpf_cnpj = 0;

    /**
     * Creates new form form_localizar_pessoas
     */
    public form_localizar_pessoas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        group_tipo.add(jCheckBox1);
        group_tipo.add(jCheckBox2);
        testar();
    }
    
    private void testar(){
        JCheckBox check1 = new JCheckBox("Test");
        jPanel1.getLayout().addLayoutComponent("Testar", check1);
    }

    
    
    /**
     * carrega informaçõe somente de pessoas fiscias
     */
    private void preencherTabelaPessoaFisica(){
        
        DefaultTableModel tabela = (DefaultTableModel)tabela_credores.getModel();
        tabela.setNumRows(0);
        
        pessoas_control control = new pessoas_control();
        List<pessoas_model> pessoaFisica = control.recuperarInfoPessoaFisica();
        
        for (pessoas_model object : pessoaFisica) {
            
            tabela.addRow(new Object[]{
                object.getId_pessoa(),
                object.getNome(),
                object.getCpf()
            });
            
        }
    }
    
       /**
     * carrega informaçõe somente de pessoas juridica
     */
    private void preencherTabelaPessoaJuridica(){
        
        DefaultTableModel tabela = (DefaultTableModel)tabela_credores.getModel();
        tabela.setNumRows(0);
        
        pessoas_control control = new pessoas_control();
        List<pessoas_model> pessoaJuridica = control.recuperarInfoPessoaJuridica();
        
        for (pessoas_model object : pessoaJuridica) {
            
            tabela.addRow(new Object[]{
                object.getId_pessoa(),
                object.getNome(),
                object.getCnpj()
            });
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_tipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_credores = new javax.swing.JTable();
        btn_selecionar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Localizar");

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/localizar_pessoas.png"))); // NOI18N
        jLabel1.setText("Localizar Pessoas ou Empresas");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jSeparator1.setBackground(new java.awt.Color(51, 0, 255));

        tabela_credores.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabela_credores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.", "Nome", "CPF/CNPJ"
            }
        ));
        tabela_credores.setShowVerticalLines(false);
        tabela_credores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_credoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_credores);
        if (tabela_credores.getColumnModel().getColumnCount() > 0) {
            tabela_credores.getColumnModel().getColumn(0).setMinWidth(40);
            tabela_credores.getColumnModel().getColumn(0).setMaxWidth(80);
            tabela_credores.getColumnModel().getColumn(1).setMinWidth(120);
            tabela_credores.getColumnModel().getColumn(1).setMaxWidth(250);
            tabela_credores.getColumnModel().getColumn(2).setMinWidth(120);
            tabela_credores.getColumnModel().getColumn(2).setMaxWidth(250);
        }

        btn_selecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/confirm_user.png"))); // NOI18N
        btn_selecionar.setEnabled(false);
        btn_selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selecionarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Localizar por:"));

        jCheckBox1.setText("CPF");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        jCheckBox2.setText("CNPJ");
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(125, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_selecionar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_selecionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selecionarActionPerformed
        //recuperando codigo do credor

        int linha = tabela_credores.getSelectedRow();
        this.codigo_pessoa = Integer.parseInt(tabela_credores.getValueAt(linha, 0).toString());
        dispose();
//        System.out.println(codigo_pessoa);

    }//GEN-LAST:event_btn_selecionarActionPerformed

    private void tabela_credoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_credoresMouseClicked
        // ativa o botao selecionar
        btn_selecionar.setEnabled(true);
    }//GEN-LAST:event_tabela_credoresMouseClicked

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        preencherTabelaPessoaFisica();
        tipo_cpf_cnpj = tipo_pessoas.CPF; // indicamos que foi feito uma busca por CPF
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
        preencherTabelaPessoaJuridica();
        tipo_cpf_cnpj = tipo_pessoas.CNPJ; // indicaos que a foi feito uma busca por CNPJ
    }//GEN-LAST:event_jCheckBox2ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_localizar_pessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_localizar_pessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_localizar_pessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_localizar_pessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form_localizar_pessoas dialog = new form_localizar_pessoas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_selecionar;
    private javax.swing.ButtonGroup group_tipo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabela_credores;
    // End of variables declaration//GEN-END:variables
}
