/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.pessoas_control;
import Model.tipo_pessoas;
import Model.pessoas_model;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.stream.IntStream;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author Andre
 */
public class form_cad_pessoas extends javax.swing.JDialog {

    /**
     * Creates new form form_cad_entrada
     */
    public form_cad_pessoas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarInfo();
    }

    /**
     * Metodo que faz a vericação se todos os campos do formulario foram preenchidos
     * @param componentes
     * @return boolean
     */
    private boolean verificarCampos(Component[] componentes) {
        boolean preenchido = true;
        for (int i = 0; i < componentes.length; i++) {
            Component componente = componentes[i];
            if (componente instanceof JTextField) {
                if (((JTextField) componente).getText().isEmpty()) {
                    ((JTextField) componente).setBorder(new LineBorder(java.awt.Color.RED));
                    preenchido = false;
                } else {
                    // campo preenchido... ok
                    ((JTextField) componente).setBorder(new LineBorder(Color.LIGHT_GRAY));
                    preenchido = true;
                }
            }
        }
        return preenchido;
    }

    /**
     * metodo criado para tratar os valores corretamente
     *
     * @param valor_entrada
     */
    private double convertValorInfo(String valor_entrada) {

        // transfroma em vetor
        IntStream s = valor_entrada.chars();
        double valor = 0;

        // verifica a qtd de posiçoes... indica numeros com casas de milhares
        if (s.count() > 6) {
            String n = valor_entrada.replace(".", "");
            String b = n.replace(",", ".");

            valor = Double.parseDouble(b);
//            System.out.println(valor);

        } else {

            // valores com casas abaixo de milhares
            String n = valor_entrada.replace(",", ".");
            valor = Double.parseDouble(n);
//            System.out.println(n);
        }

        return valor;
    }

    /**
     * carrega informações principais do formulario de entrada
     */
    private void carregarInfo() {

        grupoTipo.add(radio_cpf);
        grupoTipo.add(radio_cnpj);

        //carregando a data atual
        LocalDateTime data = LocalDateTime.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        campo_data_lancamento.setText(formato.format(data));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipo = new javax.swing.ButtonGroup();
        btn_salvar_lancamento = new javax.swing.JButton();
        formulario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campo_data_lancamento = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        campo_nome = new javax.swing.JTextField();
        lbl_cpf_cnpj = new javax.swing.JLabel();
        campo_cpf_cnpj = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        radio_cpf = new javax.swing.JRadioButton();
        radio_cnpj = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        btn_editar_cadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de novas entradas");
        setResizable(false);

        btn_salvar_lancamento.setFont(new java.awt.Font("Miriam", 1, 14)); // NOI18N
        btn_salvar_lancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Salvar_registro.png"))); // NOI18N
        btn_salvar_lancamento.setToolTipText("Salvar lancamento");
        btn_salvar_lancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_lancamentoActionPerformed(evt);
            }
        });

        formulario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informações"));

        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel2.setText("Data cadastro");

        try {
            campo_data_lancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_data_lancamento.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        campo_data_lancamento.setOpaque(false);
        campo_data_lancamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_data_lancamentoKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel7.setText("Nome:");

        campo_nome.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        campo_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_nomeKeyPressed(evt);
            }
        });

        lbl_cpf_cnpj.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbl_cpf_cnpj.setText("CPF/CNPJ:");

        campo_cpf_cnpj.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        campo_cpf_cnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_cpf_cnpjKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de cadastro"));

        radio_cpf.setText("Pessoa Fisica - CPF");
        radio_cpf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_cpfItemStateChanged(evt);
            }
        });

        radio_cnpj.setText("Pessoa Juridica - CNPJ");
        radio_cnpj.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_cnpjItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radio_cpf)
                    .addComponent(radio_cnpj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(radio_cpf)
                .addGap(18, 18, 18)
                .addComponent(radio_cnpj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout formularioLayout = new javax.swing.GroupLayout(formulario);
        formulario.setLayout(formularioLayout);
        formularioLayout.setHorizontalGroup(
            formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formularioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(lbl_cpf_cnpj))
                .addGap(25, 25, 25)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_data_lancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_cpf_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        formularioLayout.setVerticalGroup(
            formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campo_data_lancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cpf_cnpj)
                    .addComponent(campo_cpf_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(formularioLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Dotum", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cadastrar_pessoas.png"))); // NOI18N
        jLabel6.setText("Cadastro de pessoas/empresas");
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-vassoura-68.png"))); // NOI18N
        jButton1.setToolTipText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_editar_cadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/edit user.png"))); // NOI18N
        btn_editar_cadastro.setToolTipText("Alterar informaçoes");
        btn_editar_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_cadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_salvar_lancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_editar_cadastro)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_salvar_lancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_editar_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(649, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvar_lancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_lancamentoActionPerformed
        int opt = JOptionPane.showConfirmDialog(this, "Salvar as informações no banco de dados?");

        if (opt == 0) {

            if (verificarCampos(formulario.getComponents())) {

                // verificando o tipo de cadastro: CNPJ ou CPF
                if (radio_cpf.isSelected()) {

                    // recuperando dados CPF
                    pessoas_model pessoaFisica = new pessoas_model();
                    pessoaFisica.setNome(campo_nome.getText());
                    pessoaFisica.setCpf(campo_cpf_cnpj.getText());
                    pessoaFisica.setData_cadastro(campo_data_lancamento.getText());

                    pessoas_control inserir = new pessoas_control();
                    inserir.inserirPessoasEmpresas(pessoaFisica, tipo_pessoas.CPF);

                } else if (radio_cnpj.isSelected()) {

                    // recuperando dados CNPJ
                    pessoas_model pessoaJuridica = new pessoas_model();
                    pessoaJuridica.setNome(campo_nome.getText());
                    pessoaJuridica.setCnpj(campo_cpf_cnpj.getText());
                    pessoaJuridica.setData_cadastro(campo_data_lancamento.getText());

                    pessoas_control inserir = new pessoas_control();
                    inserir.inserirPessoasEmpresas(pessoaJuridica, tipo_pessoas.CNPJ);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Atenção: verifique se todos os campos foram preenchidos", "Mensagem", JOptionPane.ERROR_MESSAGE);

            }

        }

    }//GEN-LAST:event_btn_salvar_lancamentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // limpar campos
        campo_cpf_cnpj.setText("");
        campo_nome.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void campo_data_lancamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_data_lancamentoKeyPressed
        // troca de foco ao pressionar ENTER
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            campo_nome.requestFocus();
        }
    }//GEN-LAST:event_campo_data_lancamentoKeyPressed

    private void radio_cnpjItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_cnpjItemStateChanged
        campo_nome.requestFocus();
        lbl_cpf_cnpj.setText("CNPJ:");
    }//GEN-LAST:event_radio_cnpjItemStateChanged

    private void radio_cpfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_cpfItemStateChanged
        campo_nome.requestFocus();
        lbl_cpf_cnpj.setText("CPF:");
    }//GEN-LAST:event_radio_cpfItemStateChanged

    private void campo_nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_nomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            campo_cpf_cnpj.requestFocus();
        }
    }//GEN-LAST:event_campo_nomeKeyPressed

    private void campo_cpf_cnpjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_cpf_cnpjKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_salvar_lancamento.requestFocus();
        }
    }//GEN-LAST:event_campo_cpf_cnpjKeyPressed

    private void btn_editar_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_cadastroActionPerformed
        form_alterar_pessoa alterar = new form_alterar_pessoa(null, true);
        alterar.setVisible(true);
    }//GEN-LAST:event_btn_editar_cadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_cad_pessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_cad_pessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_cad_pessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_cad_pessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form_cad_pessoas dialog = new form_cad_pessoas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar_cadastro;
    private javax.swing.JButton btn_salvar_lancamento;
    private javax.swing.JTextField campo_cpf_cnpj;
    private javax.swing.JFormattedTextField campo_data_lancamento;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JPanel formulario;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_cpf_cnpj;
    private javax.swing.JRadioButton radio_cnpj;
    private javax.swing.JRadioButton radio_cpf;
    // End of variables declaration//GEN-END:variables
}
